# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: FlorilFlowersBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.markdown_transformer:
        class: FlorilFlowersBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    app.markdown_extension:
        class: FlorilFlowersBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }
#        arguments: ['@app.markdown_transformer']
        autowire: true

    app.security.login_form_authenticator:
        class: FlorilFlowersBundle\Security\LoginFormAuthenticator
        arguments: []
        autowire: true

    app.doctrine.hash_password_listener:
        class: FlorilFlowersBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - {name: doctrine.event_subscriber }

    app.formflow.register_user:
        class: FlorilFlowersBundle\Service\FormFlow\RegisterUserFlow
        parent: craue.form.flow

    app.image_uploader:
        class: FlorilFlowersBundle\Service\Upload\ImageUploader
        arguments: ['%image_directory%']

    app.database_globals_extension:
        class: FlorilFlowersBundle\Twig\Extension\DatabaseGlobalsExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    repo.promotions:
        class: FlorilFlowersBundle\Repository\Promotion\PromotionRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - FlorilFlowersBundle\Entity\Promotion\Promotion

    app.promotion_manager:
        class: FlorilFlowersBundle\Service\Promotion\PromotionManager
        arguments: ['@repo.promotions']

    app.price_calculator:
        class: FlorilFlowersBundle\Service\Promotion\PriceCalculator
        arguments: ['@app.promotion_manager', '@security.token_storage']

    app.cart_manager:
        class: FlorilFlowersBundle\Service\Cart\CartManager
        arguments: ['@doctrine.orm.entity_manager', '@session', '@app.price_calculator' ]
